name: Build Flutter APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      # Cria o local.properties na raiz do projeto, que é onde o seu Gradle está procurando
      - run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "flutter.sdk=$(flutter sdk-path)" >> local.properties
      
      # Compila o APK
      - run: flutter build apk --debug
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk